// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj7D7ffUWVjOTdHVn8N0gkmSg2BWS3cNg',
    appId: '1:626477440147:web:45e3d2d8c3d3bde9ab4166',
    messagingSenderId: '626477440147',
    projectId: 'htetmgblog',
    authDomain: 'htetmgblog.firebaseapp.com',
    storageBucket: 'htetmgblog.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlfiRaoU4mjgUshl0mIM0ZwEUX3J89qec',
    appId: '1:626477440147:android:d32971d7b86e75e2ab4166',
    messagingSenderId: '626477440147',
    projectId: 'htetmgblog',
    storageBucket: 'htetmgblog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGKWF0AXpyX2J8EfnvkZk3kPX3XTIDVzk',
    appId: '1:626477440147:ios:e04560ff419f9533ab4166',
    messagingSenderId: '626477440147',
    projectId: 'htetmgblog',
    storageBucket: 'htetmgblog.appspot.com',
    iosClientId: '626477440147-ag0j27ame5bi24eu13417ubv47a5mmhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.htetmgblog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGKWF0AXpyX2J8EfnvkZk3kPX3XTIDVzk',
    appId: '1:626477440147:ios:0343b1e4812b4b1dab4166',
    messagingSenderId: '626477440147',
    projectId: 'htetmgblog',
    storageBucket: 'htetmgblog.appspot.com',
    iosClientId: '626477440147-0dfn7soqta4bm1ck94v7kp01mpdbvdef.apps.googleusercontent.com',
    iosBundleId: 'com.example.htetmgblog.RunnerTests',
  );
}
